version: "3"
services:
  frontend:
    image: "localhost/easychat-frontend"
    restart: on-failure:5
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3000
      - VITE_HOST=localhost
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=80
    ports:
      - "8080:80"
  backend:
    image: "localhost/easychat-backend"
    restart: on-failure:5
    #ports:
    #  - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NODE_ENV=production
      - DATA_DIR=/var/lib/easychat/data
      - DATABASE_NAME=chat.sqlite3
      - LOGGING_LEVEL=error
      - LOGGING_FILES_PATH=/var/lib/easychat/logs
    volumes:
      - data:/var/lib/easychat/data
      - logs:/var/lib/easychat/logs

volumes:
  data:
  logs: